### ISSUE TITLE
Image sometimes failing to load

### ISSUE THREAD

**Issue by RobinJadoul** [FSM-Belgium/Website#1]
The image on the site fails to load from time to time.

![Failing](https://cloud.githubusercontent.com/assets/16085366/11500572/3770fe56-982e-11e5-8a3c-32a437c4e9a1.png)

But not always.

![Succeeding](https://cloud.githubusercontent.com/assets/16085366/11500585/584a614e-982e-11e5-9a4d-3f55102d341f.png)

And I cannot access the logs on the server...

**Comment by RobinJadoul** [comment]
Maybe we should let apache handle static files instead of serving them through flask

**Comment by thomasave** [comment]
Okay, I'll look into it.

**Comment by thomasave** [comment]
You should now be able to access the logs. 
I can only reproduce the issue if I really spam the refresh button for a minute or so, which causes the server to overload for a few seconds. I'm not expecting that many visitors, so I don't think it's that much of a problem. Of course, serving it through apache will probably require less load, so it might still be a good idea to change it while we're still in the early stages of development.

**Comment by RobinJadoul** [comment]
We'll probably want some caching policies from the server as well

**Comment by thomasave** [comment]
Apache is now handling the static content. I assume this issue is now closed.
